### ISSUE TITLE
Package causes SwiftUI previews not to work

### ISSUE THREAD

**Issue by PomegranateApps** [persona-id/inquiry-ios-2#1] opened 2022-09-18 14:48 UTC
When you add this package to a SwiftUI project, previews no longer work. I get this error when I try to view them.

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060000bab8f00):'PersonaInquirySDK2'>)
```

You can reproduce this by simply making a new SwiftUI project, adding this package, and then trying to view the preview in ContentView.

**Comment by PomegranateApps** [comment] 2022-09-18 14:59
This seems to be an issue with Xcode 14, but looks fixable. This same issue was reported in this package too.
https://github.com/aws-amplify/amplify-ios/issues/1874

**Comment by jacoblange-dev** [comment] 2022-09-22 23:50
Thanks for the report, we'll look into fixing and close this issue once it goes out.

**Comment by jacoblange-dev** [comment] 2022-09-23 01:23
This appears to be a wider spread Xcode issue https://developer.apple.com/forums/thread/707569. I can reproduce in Xcode 14.0 but when I test on Xcode 14.1 beta 2 the issue is fixed.

**Closed by jacoblange-dev** 2022-09-23 01:23 UTC
